### ISSUE TITLE
Viz Error with Empty Clusters (pyLDAvis,  Int64Index)

### ISSUE THREAD

**Issue by EssbieWGT** [rwalk/gsdmm#10]
Have spent a couple days trying to resolve this on my own, and am at a loss/wanted to get your thoughts. 

**Issue:** 
In trying to visualize a model run that results in multiple empty clusters, I get the following error, that I assume (perhaps incorrectly) is being causes by there being duplicate entries that are empty, given the error is being thrown at points where pandas is trying to return unique entries. The error seems to be associated with `doc_topic_dists2` but I'm not 100% sure of that either. 

Alternatively, I thought maybe the issue is that many of the rows in `doc_topic_dists2`don't sum to 1. In my case 774 of the entries don't sum to exactly 1. I'm really not sure how to fix that without just pulling every entry that doesn't sum to 1 out of the dataset, which would mean filtering out about 1/3 of all my data. 

```
#THE ERROR

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 51, in <module>
  File "<string>", line 44, in prepare_visualization_data
  File "/Users/[user]/.local/share/virtualenvs/lasocial-d_HGkGzp/lib/python3.8/site-packages/pyLDAvis/_prepare.py", line 439, in prepare topic_info = _topic_info(topic_term_dists, topic_proportion,
  File "/Users/[user]/.local/share/virtualenvs/lasocial-d_HGkGzp/lib/python3.8/site-packages/pyLDAvis/_prepare.py", line 280, in _top
ic_info
    return pd.concat([default_term_info] + list(topic_dfs))
  File "/Users/[user]/.local/share/virtualenvs/lasocial-d_HGkGzp/lib/python3.8/site-packages/pyLDAvis/_prepare.py", line 264, in topi
c_top_term_df
    term_ix = topic_terms.unique()
  File "/Users/[user]/.local/share/virtualenvs/lasocial-d_HGkGzp/lib/python3.8/site-packages/pandas/core/series.py", line 1872, in unique
result = super().unique()
  File "/Users/[user]/.local/share/virtualenvs/lasocial-d_HGkGzp/lib/python3.8/site-packages/pandas/core/base.py", line 1047, in unique
   result = unique1d(values)
  File "/Users/[user]/.local/share/virtualenvs/lasocial-d_HGkGzp/lib/python3.8/site-packages/pandas/core/algorithms.py", line 407, in
 unique
    uniques = table.unique(values)
  File "pandas/_libs/hashtable_class_helper.pxi", line 4719, in pandas._libs.hashtable.PyObjectHashTable.unique
  File "pandas/_libs/hashtable_class_helper.pxi", line 4666, in pandas._libs.hashtable.PyObjectHashTable._unique
  File "/Users/[user]/.local/share/virtualenvs/lasocial-d_HGkGzp/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 4273,
 in __hash__
    raise TypeError(f"unhashable type: {repr(type(self).__name__)}")
TypeError: unhashable type: 'Int64Index'
```
**Background:** 
Tried resolving the issue using code from a previous/related issue ([Issue #5](https://github.com/rwalk/gsdmm/issues/5)), changing the code to reflect that I'm not using iPython/a notebook. The changes are below the point where the script is throwing an error, so I don't think they're the issue, but I've included the changed lines below to make sure. 

```
def prepare_visualization_data(mgp):
    vis_data = pyLDAvis.prepare(*prepare_data(mgp), sort_topics=False)
    # with open(f"gsdmm-pyldavis-{mgp.K}-{mgp.alpha}-{mgp.beta}-{mgp.n_iters}.html", "w") as f:
    #     pyLDAvis.save_html(vis_data, f)
    return vis_data

...

vis_data = prepare_visualization_data(mgp)
pyLDAvis.save_html(vis_data, 'sttmChart.html')  # path to output
```

**What I've tried:** 
I sadly didn't catalog everything I tried in detail, but my main two efforts were as follows: 

1. First tried just converting `doc_topic_dists2` to a data frame as follows below. This however just resulted in a different error (`TypeError: '<' not supported between instances of 'list' and 'float'`) that I spent some time trying to work around but couldn't find a solution for.  

```
#how I tried to convert to dataframe

...

PDX = []
for i in doc_topic_dists2:
    PDX.append({'data':i})

docPD = pd.DataFrame(PDX)

#then... 
vis_data = pyLDAvis.prepare(matrix, docPD.data, doc_lengths, vocabulary, term_counts)

...
```

2. Tried to pull duplicates out of `doc_topic_dists2` and then filtering those duplicates out of `doc_lengths` as well so those two lists would still match up to each other. Still ran into the same `Int64Index error`, however. 

```
...
d3 = pd.DataFrame(doc_topic_dists2)
hmm = d3[d3.duplicated()]
hmmList = hmm.index.values.tolist()
for i in hmmList:
    doc_lengths.pop(i)
    doc_topic_dists2.pop(i)

#then run matrix part of the code... 
```

So I'm pretty much at a loss here. Would appreciate anyone's thoughts/ideas. Would welcome any thoughts on other ways to interactively visualize as well, as I really just need this to help my team get their head around the clustering. 

Thanks for your help!

**Comment by EssbieWGT** [comment]
Circling back on this. While it negatively affects the visualization of the model by packing the clusters more tightly together, I found that making the following two changes solved the problem. 

First, change the utils.py per [this](https://github.com/bmabey/pyLDAvis/issues/69). Next make the following update to the workaround code: 

```
    matrix = []
    for cluster in mgp.cluster_word_distribution:
        total = sum([occurance for word, occurance in cluster.items()])
        assert not math.isnan(total)
        # assert total > 0
        if total == 0:
            row = [(1 / len(vocabulary))] * len(vocabulary)   
        else:
            row = [cluster.get(term, 1) / total for term in vocabulary] # <--- updated from 0 to 1 
        for f in row:
            assert not isinstance(f, complex)
        matrix.append(row)
    return matrix, doc_topic_dists2, doc_lengths, vocabulary, term_counts
```
These two steps got the visualization working for me just fine! Will close this one out.

**Comment by ernests** [comment]
Coming back to this!
I fixed this by adding `mds='mmds'`  as a parameter to `prepare_visualization_data` function. 
As I understand, it is different dimension reduction algorithm and works if scikit is installed(https://github.com/bmabey/pyLDAvis/blob/master/pyLDAvis/_prepare.py#L337).

Solution from here - `https://github.com/bmabey/pyLDAvis/issues/69#issuecomment-311337191
