### ISSUE TITLE
 IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

### ISSUE THREAD

**Issue by spattanayak1** [rwalk/gsdmm#12]
from gsdmm.gsdmm import MovieGroupProcess

docs=[['house',
  'burning',
  'need',
  'fire',
  'truck',
  'ml',
  'hindu',
  'response',
  'christian',
  'conversion',
  'alm']]

mgp = MovieGroupProcess(K=10, alpha=0.1, beta=0.1, n_iters=30)

vocab = set(x for doc in docs for x in doc)
n_terms = len(vocab)
n_docs = len(docs)

# Fit the model on the data given the chosen seeds
y = mgp.fit(docs, n_terms)

The above code was very well working 7 days back. Suddenly we are encountering the error. Kindly advise.

**Comment by rwalk** [comment]
thank you for the issue. The recent merge from @mgallaspy seems to have broken your example.  I reverted those performance changes and added your example as a test case.  should be working now.

**Comment by spattanayak1** [comment]
Many thanks Ryan for your swift action. Really appreciated.
